debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    vanilla.witchtrial: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace # JPA 쿼리 로그 볼 수 있음. ? -> 어떤게 들어갔는지 확인 가능

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/witch-trial?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: vanilla
    password: vanille
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20

  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    open-in-view: false
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100

  h2:
    console:
      enabled: false
  sql.init.mode: always

  data.rest:
    base-path: /api
    detection-strategy: annotated

  devtools:
    livereload:
      enabled: true

  thymeleaf3:
    decoupled-logic: true

server:
  port: 8081

---

spring:
  config.activate.on-profile: testdb
  datasource:
    url: jdbc:h2:mem:board;mode=mysql
    driver-class-name: org.h2.Driver
  sql.init.mode: always
  test.database.replace: none
